-- User: новые поля
ALTER TABLE users ADD COLUMN IF NOT EXISTS first_name VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_name VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS patronymic VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS username VARCHAR;

-- Event: audit-поля
ALTER TABLE events ADD COLUMN IF NOT EXISTS last_changed_by VARCHAR;
ALTER TABLE events ADD COLUMN IF NOT EXISTS last_changed_at TIMESTAMP;
ALTER TABLE events ADD COLUMN IF NOT EXISTS last_change_action VARCHAR;
